name: generic_state_bya2
description:
  Generic State For any State Management. This package remove all the type casting hassle, and have 
  methods and classes to deal with API, Pagination Responses or your own UseCase.


repository: https://github.com/AradhyaNepal/generic_state_bya2
issue_tracker: https://github.com/AradhyaNepal/generic_state_bya2/issues
version: 0.0.9

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0